### PR TITLE
Addition of MAINTAINER.md file

### PR DESCRIPTION
**Pull request by aesop0**
For Issue #2

### CODE REVIEW

**Comment by joewxboy** [comment]
@Adam-Ayan Your commit looks fine, but was not signed-off properly.  You may have been using the Web UI instead of the CLI with the `-s` flag.  Let me see if I can enable signing off in this repo from the Web UI, or you can try amending the commit with the CLI.

**Comment by aesop0** [comment]
Hm, that's strange. Having a bit of trouble, I thought I had amended the commit message to have:
"Signed-off-by: Adam-Ayan \<adam.ayan84@gmail.com\>"
(with the quotation marks)
But the checks seem to fail still..

**Comment by joewxboy** [comment]
@Adam-Ayan Are you using the web interface to commit code or the CLI?  If you're using the web browser, then you are likely adding the sign-off as a comment instead of as a commit flag.

**Comment by aesop0** [comment]
Hi Joe, I included the commit message through the CLI and this time it still shows the DCO check as failing. Not sure what it is..

For the "Author Name" part of my signoff message what do I put? I've been putting my github username.

**Comment by joewxboy** [comment]
> Hi Joe, I included the commit message through the CLI and this time it still shows the DCO check as failing. Not sure what it is..
> 

Looking at your commits, it seems to show two separate commits.  The first one is signed-off but only contains a comment.  The second one does not have a sign-off, but it has the code.  I wonder what you're typing on the CLI?  I typically do something like:

```
git add .
git commit -s -m "issue-123: stuff changed"
git push origin issue-123
```

> For the "Author Name" part of my signoff message what do I put? I've been putting my github username.

That's probably fine.

**Comment by aesop0** [comment]
Hi Joe,

I tried the commit message you mentioned

image

DCO check still seemed unsatisfied. I thought maybe it was an issue with the commit message not having the "Signed-off-by: ......"

I tried amending it with this
image

But it looks like the presence of spaces made it not work. Because I tried this afterwards, which worked..

image

Then I tried pushing and pulling to get it to work as follows, trying things to see what happens really.

image

DCO check still ends up unsatisfied, but I'll try to keep looking into it..

**Comment by joewxboy** [comment]
OK, you almost had it right the first time.  Let's try this:

```
git config --global user.name "Adam Ayan"
git config --global user.email adam.ayan84@gmail.com
```

Then delete the PR and remove the directory.  Then clone your fork of the repo again, enter the folder, and create the issue branch before changing anything:

```
git checkout -b issue-2
```

Add the MAINTAINERS.md file, then commit:

```
git add .
git commit -s -m "Issue-2: add MAINTAINERS file"
git push origin issue-2
```

Then open the PR.

Part of the issue was the name, part was all of the commits without the `-s` flag.

**Pull request closed without merging**
